import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  // src: "./fonts/GT-Sectra-Fine-Regular.ttf",
  src: "./fonts/GT-Sectra-Regular.ttf",
  display: "swap",
  variable: "--font-sectra",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} ${myFont.className} antialiased`}
        className={` ${myFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
